version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    container_name: foodgram_backend_container_name
    image: monokrypton/foodgram_backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/backend_static
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend_container_name
    image: monokrypton/foodgram_frontend
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/
  gateway:
    container_name: foodgram_gateway_container_name
    image: monokrypton/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - frontend
      - backend
