# Generated by Django 5.0 on 2025-08-09 13:53

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Уникальный юзернейм', max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Username'),
        ),
    ]
