# Generated by Django 5.0 on 2025-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=None, help_text='Фотография профиля пользователя', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
