MAX_TAG_LENGTH = 32
MAX_EMAIL_LENGTH = 254
MAX_NAME_FIELDS_LENTGH = 150
MAX_INGRIDIENT_NAME_LENGTH = 128
MAX_UNIT_NAME_LENGTH = 64
MAX_RECIPE_NAME_LENGTH = 256
MIN_RECIPE_LENGTH_NAME = 1
MAX_LINK_LENGTH = 64
MAX_HASH_LENGTH = 10
MAX_STR_FIELD = 20
MAX_INGREDIENT_AMOUNT = 1000
MIN_INGREDIENT_AMOUNT = 1
MAX_RECIPE_LENGTH_NAME = 100
ERROR_ALREADY_FAVORITED = 'Ошибка добавления: рецепт уже в избранном'
ERROR_NO_RECIPE_FAVORITED = 'Рецепта нет в избранном'
ERROR_ALREADY_SUBSCRIBED = 'Ошибка подписки: вы уже подписаны на пользователя'
ERROR_SELF_SUBSCRIPTION = 'Ошибка подписки: нельзя подписаться на самого себя'
ERROR_ALREADY_IN_SHOPPINGCART = 'Ошибка корзины: рецепт уже в корзине'
ERROR_EMPTY_INGREDIENT = 'Ошибка создания рецепта: список ингредиентов пуст'
ERROR_DUBLICATE_INGREDIENT = 'Ошибка создания рецепта: дубликат ингредиентов'
ERROR_DUBLICATE_TAG = 'Ошибка создания рецепта: дубликат тэгов'
ERROR_EMPTY_TAG = 'Ошибка создания рецепта: список тэгов пуст'
ERROR_NO_INGREDIENT = 'Ошибка обновления рецепта: ингредиент пустой'
ERROR_NO_TAG = 'Ошибка обновления рецепта: теги пустые'
ERROR_NO_IMAGE = 'Поле image не может быть пустым'
