# Generated by Django 5.0 on 2025-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('subscribed_to')), _negated=True), name='self_subscription_unallowed'),
        ),
    ]
